package com.example.ascendlifequest.fake_data

import com.example.ascendlifequest.model.Quest
import kotlin.time.Duration.Companion.minutes

val F_Quests = listOf(
    Quest(
        id = 1,
        categorie = 1,
        nom = "Course à pied de 5 km",
        description = "Mettez vos chaussures de course et parcourez 5 kilomètres. Idéal pour un temps ensoleillé.",
        preferenceRequis = 5,
        xpRapporte = 250,
        tempsNecessaire = 30.minutes,
        dependantMeteo = true,
    ),
    Quest(
        id = 2,
        categorie = 1,
        nom = "Séance de Yoga",
        description = "Effectuez une séance de yoga de 20 minutes pour améliorer votre flexibilité et réduire le stress.",
        preferenceRequis = 4,
        xpRapporte = 180,
        tempsNecessaire = 20.minutes,
        dependantMeteo = false,
    ),
    Quest(
        id = 3,
        categorie = 1,
        nom = "Promenade en nature",
        description = "Faites une promenade relaxante dans un parc ou une forêt pour vous reconnecter avec la nature.",
        preferenceRequis = 4,
        xpRapporte = 130,
        tempsNecessaire = 30.minutes,
        dependantMeteo = true,
    ),
    Quest(
        id = 4,
        categorie = 1,
        nom = "Faire 100 pompes",
        description = "Challengez vos muscles avec une série de 100 pompes. Peut être fait en plusieurs séries.",
        preferenceRequis = 4,
        xpRapporte = 110,
        tempsNecessaire = 15.minutes,
        dependantMeteo = false,
    ),
    Quest(
        id = 5,
        categorie = 2,
        nom = "Cuisiner une nouvelle recette",
        description = "Cuisinez un repas nutritif et équilibré pour nourrir votre corps et votre esprit.",
        preferenceRequis = 5,
        xpRapporte = 200,
        tempsNecessaire = 45.minutes,
        dependantMeteo = false,
    ),
    Quest(
        id = 6,
        categorie = 2,
        nom = "Faire les courses de la semaine",
        description = "Planifiez vos repas et achetez tous les ingrédients nécessaires pour la semaine.",
        preferenceRequis = 3,
        xpRapporte = 150,
        tempsNecessaire = 60.minutes,
        dependantMeteo = false,
    ),
    Quest(
        id = 7,
        categorie = 3,
        nom = "Session de jeu d'une heure",
        description = "Détendez-vous avec votre jeu vidéo préféré. Explorez de nouveaux mondes ou affrontez des défis.",
        preferenceRequis = 4,
        xpRapporte = 160,
        tempsNecessaire = 60.minutes,
        dependantMeteo = false,
    ),
    Quest(
        id = 8,
        categorie = 3,
        nom = "Découvrir un jeu indépendant",
        description = "Essayez un nouveau jeu vidéo créé par un studio indépendant. Soutenez la créativité !",
        preferenceRequis = 3,
        xpRapporte = 120,
        tempsNecessaire = 45.minutes,
        dependantMeteo = false,
    ),
    Quest(
        id = 9,
        categorie = 4,
        nom = "Lire un chapitre d'un livre",
        description = "Prenez du temps pour vous et plongez dans un bon livre. Lisez au moins un chapitre.",
        preferenceRequis = 3,
        xpRapporte = 100,
        tempsNecessaire = 20.minutes,
        dependantMeteo = false,
    ),
    Quest(
        id = 10,
        categorie = 4,
        nom = "Écouter un podcast littéraire",
        description = "Découvrez de nouvelles perspectives sur la littérature en écoutant un podcast dédié aux livres.",
        preferenceRequis = 4,
        xpRapporte = 120,
        tempsNecessaire = 25.minutes,
        dependantMeteo = false,
    )
)