name: Bug Report
description: Signaler un bug dans l'application
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug !

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug
      placeholder: Décrivez le problème rencontré
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire ce bug ?
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Faire défiler jusqu'à '...'
        4. Observer l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
      placeholder: Décrivez le comportement attendu
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il réellement ?
      placeholder: Décrivez ce qui se passe
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si applicable, ajoutez des screenshots
      placeholder: Glissez-déposez vos images ici

  - type: input
    id: android-version
    attributes:
      label: Version Android
      placeholder: "ex: Android 13"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Appareil
      placeholder: "ex: Samsung Galaxy S23"
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: Version de l'application
      placeholder: "ex: 1.0.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Logs pertinents (si disponibles)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Toute information supplémentaire sur le problème
